camel.labs.iot.cloudlet.document.driver.mongodb.db: cloudlet_geofencing
server.port: 15000
spring:
  data.mongodb.database: ${camel.labs.iot.cloudlet.document.driver.mongodb.db}
  main.sources: com.github.camellabs.iot.cloudlet.geofencing.GeofencingCloudlet